### ISSUE TITLE
TCP option for the docker engine connection

### ISSUE THREAD

**Issue by ivanilves** [ivanilves/lstags#93]
I think the idea from @solidnerd PR https://github.com/ivanilves/lstags/pull/92 should be implemented.

**Comment by solidnerd** [comment]
I think one of low hanging fruit would be to use `client.NewEnvClient()` instead of the current implementation in https://github.com/ivanilves/lstags/blob/master/docker/client/client.go#L33 .

**Comment by vonrabbe** [comment]
@ivanilves I consider this critical.

:exclamation: We need to have tcp for docker to preload images on our swarm fleet machines. :pray:

**Comment by vonrabbe** [comment]
I propose to do this first https://github.com/ivanilves/lstags/issues/29 and then immediately do the TCP thing.

WDYT?

**Comment by solidnerd** [comment]
@ivanilves @vonrabbe  I would grab me this and try to solve it if you want. I think this would gives this tool a big improvement how you can handle that. 
I think #94  is not the correct way because now we are skipping the tests during a docker build and this should be not case. When we are introducing the tcp option it's also possible to have the tests during the docker build and we can revert the assemble job in the makefile.

**Comment by ivanilves** [comment]
You are welcome to grab this @solidnerd :muscle:

Yes https://github.com/ivanilves/lstags/pull/94 is not the best way. We just needed something to start fast and simple.

**Comment by ivanilves** [comment]
Hey @solidnerd did you have any time to look at this?

**Comment by ivanilves** [comment]
Closing this in favor of https://github.com/ivanilves/lstags/issues/102 (to narrow focus)
